### ISSUE TITLE
Plugin Approval

### ISSUE THREAD

**Issue by NyakudyaA** [Newton787/POLO-plugin#1]
Please put a small english description so that users can get some idea of what the plugin does.

**Comment by NyakudyaA** [comment]
ping @Newton787

**Comment by NyakudyaA** [comment]
ping @Newton787

**Comment by Newton787** [comment]
It’s done. I’ve translated the text into English, but the plugin is in Portuguese because the scope of operation is restricted to the state of Amazonas, Brazil, with the plugin being primarily utilized by Brazilian users
